server:
  port: 8082
dubbo:
  application:
    name: service-consumers
    id: service-consumers
  registry:
    address: 192.168.38.142
    port: 2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20899
    host:
spring:
  main:
    allow-bean-definition-overriding: true